### PR TITLE
A2600 support

### PR DESCRIPTION
**Pull request by vossstef**
Atari 2600 console support

### CODE REVIEW

**Comment by harbaum** [comment]
The file selection using those various extensions does work and the extra list of extensions is only a workaround until the firmware can report which extension it has used. Right?

**Comment by vossstef** [comment]
> The file selection using those various extensions does work and the extra list of extensions is only a workaround until the firmware can report which extension it has used. Right?

unfortunately this workaround is not that usable as i initially thought and looks that i need the correct extension via a firmware enhancement. i am just looking what could be done maybe core specific with as little effort as posible.

**Comment by harbaum** [comment]
I'll build something the coming week ...

**Comment by vossstef** [comment]
> I'll build something the coming week ...

Hi Till, i found a solution based on a module from the Atari 7800 sources. Extension based control of mapper is not so important anymore. User experience is anyway better by autodetection rather than rename of tons of .bin into correct extension.

**Comment by harbaum** [comment]
Sending the "index of the extension in the list" as suggested via PM would not work as the image can also be loaded on startup and in that case the list of valid extensions is no present.

I thus just pushed a small change such that the Companion would send the null terminated extension with the image length. Old cores would (hopefully) just ignore the additional bytes but newer cores can evaluate it.

**Comment by harbaum** [comment]
The following (untested) code is supposed to work with this on FPGA side:

```
			// SDC CMD 4: INSERTED
			if(command == 8'd4) begin
			   // MCU reports that some image has been inserted. If
			   // the image size is 0, then no image is inserted
			   if(byte_cnt == 4'd0) image_target <= data_in;
			   // read image length
			   if(byte_cnt == 4'd1) image_size[31:24] <= data_in;
			   if(byte_cnt == 4'd2) image_size[23:16] <= data_in;
			   if(byte_cnt == 4'd3) image_size[15:8]  <= data_in;
			   if(byte_cnt == 4'd4) image_size[ 7:0]  <= data_in;
			   // read 0 terminated file name extension
			   if(byte_cnt >= 4'd5) begin
				  // check of end of extension has been reached
				  if(data_in != 8'd0) begin
				  	 // analyze extension characters
					 if(byte_cnt == 4'd5) ext_chr_0 <= data_in;
					 if(byte_cnt == 4'd6) ext_chr_1 <= data_in;
					 if(byte_cnt == 4'd7) ext_chr_2 <= data_in;
					 // ... 
				  end else begin
					 // check e.g. for two byte long extension "AB"
					 if ( byte_cnt == 4'd7 && ext_chr_0 == "A" &&  ext_chr_0 == "B" )
					   extension <= FILE_TYPE_AB;
					 					 
					 image_mounted[image_target] <= 1'b1;
				  end
			   end
			end
```

**Comment by vossstef** [comment]
Many Thanks !

**Pull request merged**
